// Package neutral reflects Go DTO structs into the language-neutral field
// vocabulary the cross-language conformance corpus freezes. It is the ONE place
// the Go→neutral mapping lives, shared by the two generators (the chatd-hosted
// gateway generator in package main and the external turnresult generator under
// test/conformance) so both emit identical `fields.json` shapes.
//
// The neutral type vocabulary is deliberately small — string / int / bool /
// array / object / ref / any / timestamp — and hides every Go-side distinction a
// TypeScript consumer cannot see: pointer vs value, omitempty vs omitzero, and
// the concrete Go type name behind a nested DTO. See test/conformance/README.md.
package neutral

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strings"
	"time"
)

// FieldInfo is one struct field's neutral, language-neutral descriptor. The Go
// field name is kept as a stable identifier; json_tag is the wire key a
// consumer matches on; type is the neutral vocabulary; optional is the single
// boolean collapsing all three Go-side optionality sources (pointer, omitempty,
// omitzero).
type FieldInfo struct {
	Name     string `json:"name"`
	JSONTag  string `json:"json_tag"`
	Type     string `json:"type"`
	Optional bool   `json:"optional"`
}

// Fields reflects a struct value into its ordered neutral field descriptors,
// preserving struct-declaration order. Fields tagged json:"-" (internal store
// metadata, never on the public wire) are excluded.
func Fields(v any) []FieldInfo {
	rt := reflect.TypeOf(v)
	for rt.Kind() == reflect.Pointer {
		rt = rt.Elem()
	}
	out := make([]FieldInfo, 0, rt.NumField())
	for i := 0; i < rt.NumField(); i++ {
		f := rt.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue // json:"-": internal, excluded from the public contract
		}
		name, opts := splitTag(tag)
		if name == "" {
			name = f.Name // an untagged field serializes under its Go name
		}
		optional := f.Type.Kind() == reflect.Pointer ||
			hasOpt(opts, "omitempty") ||
			hasOpt(opts, "omitzero")
		out = append(out, FieldInfo{
			Name:     f.Name,
			JSONTag:  name,
			Type:     NeutralType(f.Type),
			Optional: optional,
		})
	}
	return out
}

// FieldsFor builds the DTO-name → ordered-fields map for a set of struct
// values. The top-level map marshals with sorted DTO names (encoding/json sorts
// map keys); each field slice keeps declaration order — together giving the
// deterministic byte form the manifest hash depends on.
func FieldsFor(vs ...any) map[string][]FieldInfo {
	m := make(map[string][]FieldInfo, len(vs))
	for _, v := range vs {
		rt := reflect.TypeOf(v)
		for rt.Kind() == reflect.Pointer {
			rt = rt.Elem()
		}
		m[rt.Name()] = Fields(v)
	}
	return m
}

// Marshal emits deterministic, pretty-printed JSON for a fields map: sorted DTO
// names (map-key sort), declaration-order fields, two-space indent, and a
// trailing newline. Regenerated bytes are reproducible.
func Marshal(m map[string][]FieldInfo) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(m); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

var timeType = reflect.TypeOf(time.Time{})

// NeutralType maps a Go type to the neutral vocabulary. Pointers are
// transparent (optionality is captured separately). time.Time → timestamp;
// json.RawMessage / []byte → any (arbitrary JSON value); byte-slices aside,
// slices/arrays → array; maps and anonymous structs → object; a named struct
// (a nested DTO) → ref; interfaces → any.
func NeutralType(t reflect.Type) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Bool:
		return "bool"
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "int"
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			// json.RawMessage (and any []byte) is an arbitrary JSON value.
			return "any"
		}
		return "array"
	case reflect.Map:
		return "object"
	case reflect.Struct:
		if t == timeType {
			return "timestamp"
		}
		if t.Name() == "" {
			return "object" // anonymous inline struct
		}
		return "ref"
	case reflect.Interface:
		return "any"
	default:
		return "any"
	}
}

// splitTag returns the json tag's name and the remaining comma options.
func splitTag(tag string) (name, opts string) {
	if i := strings.IndexByte(tag, ','); i >= 0 {
		return tag[:i], tag[i+1:]
	}
	return tag, ""
}

// hasOpt reports whether a comma-joined option list contains opt.
func hasOpt(opts, opt string) bool {
	for opts != "" {
		var cur string
		if i := strings.IndexByte(opts, ','); i >= 0 {
			cur, opts = opts[:i], opts[i+1:]
		} else {
			cur, opts = opts, ""
		}
		if cur == opt {
			return true
		}
	}
	return false
}
