// Package apparmor is harness-wrapper's AppArmor socket layer: the one static
// profile a contained launch stacks onto the harness when the kernel's Landlock
// ABI predates RESOLVE_UNIX (ADR-005). Landlock stays the filesystem, network
// and IPC boundary; the profile only withholds write access — which connecting
// to a pathname UNIX socket requires — outside a fixed set of roots and the
// device nodes a harness writes, so a harness cannot reach the D-Bus, systemd,
// container-runtime or SSH-agent sockets Landlock below ABI 9 leaves open.
//
// The profile is generated here (Profile), installed and loaded by root, and
// never changed by the wrapper. Its first line records the roots it allows, so
// a launch can refuse a writable grant the profile would break.
package apparmor

import (
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

// ProfileName is the name of the profile a contained launch stacks.
const ProfileName = "harness-wrapper-contain"

// PolicyPath is where the profile's source is installed. A launch reads its
// roots from this file, so it must be owned by root and writable by no one
// else.
const PolicyPath = "/etc/apparmor.d/" + ProfileName

// FormatVersion versions the header line. Readers refuse versions they do not
// know.
const FormatVersion = 1

// headerPrefix starts the profile's first line; the JSON root list follows.
var headerPrefix = fmt.Sprintf("# %s v%d roots: ", ProfileName, FormatVersion)

// Devices are the device nodes the profile lets a harness write, beyond its
// roots: every device a harness profile grants write access to, and the
// session terminal (a /dev/pts slave), which the harness inherits as
// descriptors 0-2 and reopens as /dev/tty. AppArmor revalidates inherited
// descriptors at the stacking exec, so a terminal missing here would be
// replaced before the harness runs.
var Devices = []string{"/dev/null", "/dev/tty"}

// terminalPattern is the AppArmor pattern for a session terminal.
const terminalPattern = "/dev/pts/[0-9]*"

// ErrInvalidRoot is wrapped by every root the profile cannot carry.
var ErrInvalidRoot = errors.New("apparmor: invalid root")

// safeRoot admits only characters that mean nothing to the AppArmor policy
// language inside a quoted path: no globbing (* ? [ ] { } ^), no variables
// (@), no quotes, escapes, whitespace or control characters.
var safeRoot = regexp.MustCompile(`^[A-Za-z0-9._+\-/~:=%]+$`)

// ValidateRoot reports whether root can be a profile root: an absolute,
// clean path other than "/" made only of characters the policy language
// takes literally.
func ValidateRoot(root string) error {
	switch {
	case root == "" || !filepath.IsAbs(root):
		return fmt.Errorf("%w: %q is not an absolute path", ErrInvalidRoot, root)
	case filepath.Clean(root) != root:
		return fmt.Errorf("%w: %q is not clean (want %q)", ErrInvalidRoot, root, filepath.Clean(root))
	case root == "/":
		return fmt.Errorf("%w: \"/\" would allow writing, and so connecting to, every socket on the host", ErrInvalidRoot)
	case !safeRoot.MatchString(root):
		return fmt.Errorf("%w: %q contains a character outside [A-Za-z0-9._+-/~:=%%], which AppArmor could read as a pattern", ErrInvalidRoot, root)
	}
	return nil
}

// Profile returns the profile source for roots: sorted, duplicates removed,
// each validated with ValidateRoot. It needs at least one root.
func Profile(roots []string) (string, error) {
	roots, err := normalizeRoots(roots)
	if err != nil {
		return "", err
	}
	header, _ := json.Marshal(roots)
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("%s%s", headerPrefix, header)
	w("#")
	w("# Generated by `harness-wrapper contain-apparmor-profile`. Do not edit: the")
	w("# line above is what a contained launch reads. Regenerate it, install it as")
	w("# %s and load it with", PolicyPath)
	w("#   apparmor_parser -r %s", PolicyPath)
	w("#")
	w("# harness-wrapper stacks this profile onto a contained harness when the")
	w("# kernel's Landlock ABI predates RESOLVE_UNIX (ADR-005). Landlock stays the")
	w("# filesystem and network boundary; this profile only withholds write access,")
	w("# which connecting to a pathname UNIX socket requires, outside the roots")
	w("# below and the devices a harness writes.")
	w("abi <abi/3.0>,")
	w("")
	w("profile %s flags=(attach_disconnected,mediate_deleted) {", ProfileName)
	w("  capability,")
	w("  network,")
	w("  unix,")
	w("  signal,")
	w("  ptrace,")
	w("  mount,")
	w("  umount,")
	w("  pivot_root,")
	w("  dbus,")
	w("")
	w("  # Everything but write and append, everywhere: Landlock decides the rest.")
	w("  /** rmixlk,")
	w("")
	for _, d := range Devices {
		w("  %s rw,", d)
	}
	w("  %s rw,", terminalPattern)
	w("")
	for _, r := range roots {
		w("  \"%s/{,**}\" rw,", r)
	}
	w("}")
	return b.String(), nil
}

// ParseRoots reads the roots from a profile source's header line.
func ParseRoots(src []byte) ([]string, error) {
	line, _, _ := strings.Cut(string(src), "\n")
	rest, ok := strings.CutPrefix(line, headerPrefix)
	if !ok {
		if strings.HasPrefix(line, "# "+ProfileName+" v") {
			return nil, fmt.Errorf("apparmor: %s has an unknown header version: %q", PolicyPath, line)
		}
		return nil, fmt.Errorf("apparmor: %s does not start with a %q header; regenerate it with harness-wrapper contain-apparmor-profile", PolicyPath, headerPrefix)
	}
	var roots []string
	if err := json.Unmarshal([]byte(rest), &roots); err != nil {
		return nil, fmt.Errorf("apparmor: %s header: %w", PolicyPath, err)
	}
	return normalizeRoots(roots)
}

func normalizeRoots(roots []string) ([]string, error) {
	if len(roots) == 0 {
		return nil, fmt.Errorf("%w: the profile needs at least one root", ErrInvalidRoot)
	}
	for _, r := range roots {
		if err := ValidateRoot(r); err != nil {
			return nil, err
		}
	}
	out := slices.Clone(roots)
	slices.Sort(out)
	return slices.Compact(out), nil
}

// Covers reports whether path (canonical) is one of roots or lies beneath one.
func Covers(roots []string, path string) bool {
	for _, r := range roots {
		if path == r || strings.HasPrefix(path, r+"/") {
			return true
		}
	}
	return false
}

// Layer is the installed socket layer a launch stacks.
type Layer struct {
	// Roots are the directories beneath which the profile allows writes and
	// pathname-socket connects.
	Roots []string
}

// Covers reports whether path (canonical) lies beneath one of l's roots.
func (l *Layer) Covers(path string) bool { return Covers(l.Roots, path) }

// labelHas reports whether an AppArmor label, as /proc/<pid>/attr/apparmor/
// current prints it, includes profile in enforce mode. A stack prints as
// "a//&b (enforce)" when every component shares a mode, and with a mode per
// component otherwise; a component without its own mode takes the trailing
// one. Anything else — no mode, complain, a mode it cannot attribute — is
// false.
func labelHas(label, profile string) bool {
	parts := strings.Split(strings.TrimSpace(label), "//&")
	trailing := ""
	if last := parts[len(parts)-1]; strings.HasSuffix(last, ")") {
		if i := strings.LastIndex(last, " ("); i >= 0 {
			trailing = last[i+2 : len(last)-1]
			parts[len(parts)-1] = last[:i]
		}
	}
	for _, p := range parts {
		name, mode := p, trailing
		if strings.HasSuffix(p, ")") {
			if i := strings.LastIndex(p, " ("); i >= 0 {
				name, mode = p[:i], p[i+2:len(p)-1]
			}
		}
		if name == profile {
			return mode == "enforce"
		}
	}
	return false
}
