// Command facadegen writes a facade package's declarations: one per exported
// top-level identifier of a core package — a type alias, a re-declared const or
// var, or a forwarding func. pkg/wrapper and pkg/chat are such facades over
// internal/wrapcore and internal/chatcore; each regenerates its file with
// go generate.
//
//	facadegen -core DIR -import PATH -alias NAME -pkg NAME [-skip a,b] -o FILE
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// skipped holds the identifiers the facade leaves out; a signature naming one
// of those types must qualify it.
var skipped = map[string]bool{}

func main() {
	dir := flag.String("core", "", "core package directory")
	importPath := flag.String("import", "", "core import path")
	alias := flag.String("alias", "core", "name the facade imports the core as")
	pkg := flag.String("pkg", "", "facade package name")
	skipList := flag.String("skip", "", "comma-separated identifiers to leave out")
	outFile := flag.String("o", "", "file to write (default: standard output)")
	flag.Parse()
	skip := skipped
	for _, s := range strings.Split(*skipList, ",") {
		if s != "" {
			skip[s] = true
		}
	}

	fset := token.NewFileSet()
	entries, err := os.ReadDir(*dir)
	if err != nil {
		fatal(err)
	}
	var files []*ast.File
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(*dir, name), nil, parser.ParseComments)
		if err != nil {
			fatal(err)
		}
		files = append(files, f)
	}
	if len(files) == 0 {
		fatal(fmt.Errorf("no Go files in %s", *dir))
	}

	// Exported type names declared in the core: a bare reference to one in a
	// func signature is qualified with the alias.
	coreTypes := map[string]bool{}
	for _, f := range files {
		for _, d := range f.Decls {
			if gd, ok := d.(*ast.GenDecl); ok && gd.Tok == token.TYPE {
				for _, sp := range gd.Specs {
					ts := sp.(*ast.TypeSpec)
					coreTypes[ts.Name.Name] = true
				}
			}
		}
	}

	var types, consts, vars, funcs []string
	// An identifier declared once per build-constrained file (linux and
	// other) is forwarded once.
	seen := map[string]bool{}
	first := func(n string) bool {
		if seen[n] {
			return false
		}
		seen[n] = true
		return true
	}
	imports := map[string]string{} // name -> path, for funcs' signatures
	for _, f := range files {
		fileImports := map[string]string{}
		for _, im := range f.Imports {
			path := strings.Trim(im.Path.Value, `"`)
			name := filepath.Base(path)
			if im.Name != nil {
				name = im.Name.Name
			}
			fileImports[name] = path
		}
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.GenDecl:
				for _, sp := range d.Specs {
					switch sp := sp.(type) {
					case *ast.TypeSpec:
						n := sp.Name.Name
						if !ast.IsExported(n) || skip[n] || !first(n) {
							continue
						}
						if sp.TypeParams != nil {
							fatal(fmt.Errorf("generic type %s: not supported", n))
						}
						types = append(types, fmt.Sprintf("// %s is %s.%s.\ntype %s = %s.%s\n", n, *alias, n, n, *alias, n))
					case *ast.ValueSpec:
						for _, id := range sp.Names {
							n := id.Name
							if !ast.IsExported(n) || skip[n] || !first(n) {
								continue
							}
							line := fmt.Sprintf("\t%s = %s.%s\n", n, *alias, n)
							if d.Tok == token.CONST {
								consts = append(consts, line)
							} else {
								vars = append(vars, line)
							}
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv != nil || !ast.IsExported(d.Name.Name) || skip[d.Name.Name] || !first(d.Name.Name) {
					continue
				}
				if d.Type.TypeParams != nil {
					fatal(fmt.Errorf("generic func %s: not supported", d.Name.Name))
				}
				funcs = append(funcs, renderFunc(fset, d, *alias, coreTypes, fileImports, imports))
			}
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by facadegen from %s. DO NOT EDIT.\n\n", *importPath)
	fmt.Fprintf(&b, "package %s\n\nimport (\n", *pkg)
	// The standard library first, then a blank line, then the module's
	// packages: the grouping gci keeps, so go generate and the formatter
	// agree.
	var std, mod []string
	imports[*alias] = *importPath
	for name, path := range imports {
		line := fmt.Sprintf("\t%q\n", path)
		if name != filepath.Base(path) {
			line = fmt.Sprintf("\t%s %q\n", name, path)
		}
		if strings.Contains(strings.SplitN(path, "/", 2)[0], ".") {
			mod = append(mod, line)
		} else {
			std = append(std, line)
		}
	}
	sort.Slice(std, func(i, j int) bool { return importPathOf(std[i]) < importPathOf(std[j]) })
	sort.Slice(mod, func(i, j int) bool { return importPathOf(mod[i]) < importPathOf(mod[j]) })
	b.WriteString(strings.Join(std, ""))
	if len(std) > 0 && len(mod) > 0 {
		b.WriteString("\n")
	}
	b.WriteString(strings.Join(mod, ""))
	b.WriteString(")\n\n")
	for _, t := range types {
		b.WriteString(t)
		b.WriteString("\n")
	}
	if len(consts) > 0 {
		fmt.Fprintf(&b, "// Constants of %s.\nconst (\n%s)\n\n", *alias, strings.Join(consts, ""))
	}
	if len(vars) > 0 {
		fmt.Fprintf(&b, "// Variables of %s. Each holds the same value as its original, so errors.Is\n// and comparisons match either.\nvar (\n%s)\n\n", *alias, strings.Join(vars, ""))
	}
	for _, fn := range funcs {
		b.WriteString(fn)
		b.WriteString("\n")
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		_, _ = os.Stdout.Write(b.Bytes())
		fatal(err)
	}
	if *outFile == "" {
		_, _ = os.Stdout.Write(out)
		return
	}
	if err := os.WriteFile(*outFile, out, 0o644); err != nil {
		fatal(err)
	}
}

func renderFunc(fset *token.FileSet, d *ast.FuncDecl, alias string, coreTypes map[string]bool, fileImports, used map[string]string) string {
	qual := func(e ast.Expr) string {
		// Qualify bare core type names; note imported packages used.
		e = qualify(e, alias, coreTypes, fileImports, used)
		var buf bytes.Buffer
		if err := format.Node(&buf, fset, e); err != nil {
			fatal(err)
		}
		return buf.String()
	}
	var params, args []string
	variadic := false
	i := 0
	for _, fld := range d.Type.Params.List {
		typ := qual(fld.Type)
		if _, ok := fld.Type.(*ast.Ellipsis); ok {
			variadic = true
		}
		if len(fld.Names) == 0 {
			n := fmt.Sprintf("a%d", i)
			i++
			params = append(params, n+" "+typ)
			args = append(args, n)
			continue
		}
		for _, n := range fld.Names {
			name := n.Name
			if name == "_" {
				name = fmt.Sprintf("a%d", i)
			}
			i++
			params = append(params, name+" "+typ)
			args = append(args, name)
		}
	}
	if variadic {
		args[len(args)-1] += "..."
	}
	var results []string
	if d.Type.Results != nil {
		for _, fld := range d.Type.Results.List {
			typ := qual(fld.Type)
			n := len(fld.Names)
			if n == 0 {
				n = 1
			}
			for k := 0; k < n; k++ {
				results = append(results, typ)
			}
		}
	}
	res := ""
	switch len(results) {
	case 0:
	case 1:
		res = " " + results[0]
	default:
		res = " (" + strings.Join(results, ", ") + ")"
	}
	call := fmt.Sprintf("%s.%s(%s)", alias, d.Name.Name, strings.Join(args, ", "))
	body := "return " + call
	if len(results) == 0 {
		body = call
	}
	return fmt.Sprintf("// %s calls %s.%s.\nfunc %s(%s)%s {\n\t%s\n}\n", d.Name.Name, alias, d.Name.Name, d.Name.Name, strings.Join(params, ", "), res, body)
}

// qualify returns a copy of e with bare exported core type identifiers
// qualified by alias, recording the imports selector expressions use.
func qualify(e ast.Expr, alias string, coreTypes map[string]bool, fileImports, used map[string]string) ast.Expr {
	switch t := e.(type) {
	case *ast.Ident:
		if coreTypes[t.Name] {
			if !ast.IsExported(t.Name) {
				fatal(fmt.Errorf("unexported core type %s in an exported signature", t.Name))
			}
			if skipped[t.Name] {
				return &ast.SelectorExpr{X: ast.NewIdent(alias), Sel: ast.NewIdent(t.Name)}
			}
			return t // the facade declares an alias of the same name
		}
		return t
	case *ast.SelectorExpr:
		if x, ok := t.X.(*ast.Ident); ok {
			if path, ok := fileImports[x.Name]; ok {
				used[x.Name] = path
			}
		}
		return t
	case *ast.StarExpr:
		return &ast.StarExpr{X: qualify(t.X, alias, coreTypes, fileImports, used)}
	case *ast.ArrayType:
		return &ast.ArrayType{Len: t.Len, Elt: qualify(t.Elt, alias, coreTypes, fileImports, used)}
	case *ast.MapType:
		return &ast.MapType{Key: qualify(t.Key, alias, coreTypes, fileImports, used), Value: qualify(t.Value, alias, coreTypes, fileImports, used)}
	case *ast.ChanType:
		return &ast.ChanType{Dir: t.Dir, Value: qualify(t.Value, alias, coreTypes, fileImports, used)}
	case *ast.Ellipsis:
		return &ast.Ellipsis{Elt: qualify(t.Elt, alias, coreTypes, fileImports, used)}
	case *ast.FuncType:
		nt := &ast.FuncType{Params: qualifyFields(t.Params, alias, coreTypes, fileImports, used), Results: qualifyFields(t.Results, alias, coreTypes, fileImports, used)}
		return nt
	case *ast.InterfaceType, *ast.StructType:
		if hasFields(t) {
			fatal(fmt.Errorf("inline struct/interface type in an exported signature: not supported"))
		}
		return t
	default:
		return e
	}
}

func hasFields(e ast.Expr) bool {
	switch t := e.(type) {
	case *ast.InterfaceType:
		return t.Methods != nil && len(t.Methods.List) > 0
	case *ast.StructType:
		return t.Fields != nil && len(t.Fields.List) > 0
	}
	return false
}

func qualifyFields(fl *ast.FieldList, alias string, coreTypes map[string]bool, fileImports, used map[string]string) *ast.FieldList {
	if fl == nil {
		return nil
	}
	out := &ast.FieldList{}
	for _, f := range fl.List {
		out.List = append(out.List, &ast.Field{Names: f.Names, Type: qualify(f.Type, alias, coreTypes, fileImports, used)})
	}
	return out
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "facadegen:", err)
	os.Exit(1)
}

// importPathOf is the quoted path of an import line.
func importPathOf(line string) string {
	i := strings.Index(line, `"`)
	return line[i:]
}
