// Package conformance hosts the external (exported-symbol) slice of the
// cross-language conformance corpus: the StructuredTurnResult turnresult
// fixtures + fields, the cli exit-code table, and the whole-corpus
// MANIFEST.sha256. It works against the exported pkg/turnproto and
// pkg/transcript symbols; the gateway slice, whose DTOs are unexported package
// main types, is generated by cmd/harness-chatd/conformance_test.go instead.
//
// Regenerate the WHOLE corpus in order with: make regen-conformance
// (chatd package first — it writes gateway/ — then this package, which writes
// turnresult/ + cli/ and finally hashes the whole tree). A plain `go test`
// round-trips fixtures and asserts every golden + the manifest match.
//
// See README.md for the convention (neutral vocabulary, structural comparison,
// determinism, manifest-guards-integrity-only).
package conformance

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/olesho/harness-wrapper/pkg/transcript"
	"github.com/olesho/harness-wrapper/pkg/turnproto"
	"github.com/olesho/harness-wrapper/test/conformance/neutral"
)

// turnStatuses is the frozen status enumeration, in emit order.
var turnStatuses = []turnproto.TurnStatus{
	turnproto.StatusCompleted,
	turnproto.StatusErrored,
	turnproto.StatusDeadline,
	turnproto.StatusStartupError,
}

// turnFixture is one StructuredTurnResult example instance plus its filename.
type turnFixture struct {
	name  string
	value turnproto.StructuredTurnResult
}

func mustTime(s string) time.Time {
	tm, err := time.Parse(time.RFC3339, s)
	if err != nil {
		panic(err)
	}
	return tm
}

// turnFixtures covers each TurnStatus, the present/absent variants of the
// omitempty optionals (reason, transcript_error, usage, permission_mode), and
// — critically — a
// completed fixture whose transcript_entries carry tool_use / tool_result
// events (ToolInput as raw JSON, omitempty Text/Output across event types),
// where cross-language structural comparison is most likely to catch a bug.
func turnFixtures() []turnFixture {
	ts := mustTime("2026-07-21T10:00:00Z")
	textEntries := []transcript.Event{
		{Seq: 1, Timestamp: ts, Role: transcript.RoleUser, Type: transcript.EventText, Text: "do the thing"},
		{Seq: 2, Timestamp: ts, Role: transcript.RoleAssistant, Type: transcript.EventText, Text: "done"},
	}
	toolEntries := []transcript.Event{
		{Seq: 1, Timestamp: ts, Role: transcript.RoleAssistant, Type: transcript.EventText, Text: "running a tool"},
		{
			Seq: 2, Timestamp: ts, Role: transcript.RoleAssistant, Type: transcript.EventToolUse,
			ToolName: "Bash", ToolUseID: "tu_1", ToolInput: json.RawMessage(`{"command":"ls -la"}`),
		},
		{
			Seq: 3, Timestamp: ts, Role: transcript.RoleTool, Type: transcript.EventToolResult,
			ToolUseID: "tu_1", Output: "total 0\n",
		},
	}
	return []turnFixture{
		// completed, all three optionals ABSENT (omitempty drops reason /
		// transcript_error / usage).
		{"StructuredTurnResult.completed", turnproto.StructuredTurnResult{
			Status: turnproto.StatusCompleted, Reply: "done", HarnessSessionID: "sess-1",
			TranscriptEntries: textEntries, WorkingDir: "/work",
		}},
		// completed with tool_use / tool_result entries — the raw-JSON ToolInput
		// and cross-event omitempty behavior TS is most likely to get wrong.
		{"StructuredTurnResult.completed_tool_calls", turnproto.StructuredTurnResult{
			Status: turnproto.StatusCompleted, Reply: "ran ls", HarnessSessionID: "sess-2",
			TranscriptEntries: toolEntries, WorkingDir: "/work",
		}},
		// completed carrying usage — all five inner keys present (including zeros).
		{"StructuredTurnResult.completed_usage", turnproto.StructuredTurnResult{
			Status: turnproto.StatusCompleted, Reply: "done", HarnessSessionID: "sess-3",
			TranscriptEntries: textEntries, WorkingDir: "/work",
			Usage: &transcript.Usage{InputTokens: 100, OutputTokens: 50, CacheReadInputTokens: 20},
		}},
		// completed with a best-effort transcript read failure — transcript_error
		// PRESENT while entries stayed empty.
		{"StructuredTurnResult.completed_transcript_error", turnproto.StructuredTurnResult{
			Status: turnproto.StatusCompleted, Reply: "done", HarnessSessionID: "sess-4",
			TranscriptEntries: []transcript.Event{}, WorkingDir: "/work",
			TranscriptError: "read transcript: no session file",
		}},
		// errored — reason PRESENT, empty reply.
		{"StructuredTurnResult.errored", turnproto.StructuredTurnResult{
			Status: turnproto.StatusErrored, HarnessSessionID: "sess-5",
			TranscriptEntries: []transcript.Event{}, WorkingDir: "/work",
			Reason: "harness exited non-zero",
		}},
		// deadline — empty reply, no reason.
		{"StructuredTurnResult.deadline", turnproto.StructuredTurnResult{
			Status: turnproto.StatusDeadline, HarnessSessionID: "sess-6",
			TranscriptEntries: []transcript.Event{}, WorkingDir: "/work",
		}},
		// startup_error — reason PRESENT, no session id recovered. permission_mode
		// is ABSENT by rule, not by accident: no harness was launched, so there is
		// no rung to report (see StructuredTurnResult.PermissionMode).
		{"StructuredTurnResult.startup_error", turnproto.StructuredTurnResult{
			Status:            turnproto.StatusStartupError,
			TranscriptEntries: []transcript.Event{}, WorkingDir: "/work",
			Reason: "empty prompt",
		}},
		// completed carrying permission_mode — the present variant of the fourth
		// omitempty optional; StructuredTurnResult.completed above is the omitted
		// variant. The value is a CANONICAL RUNG ("bypass"), never a harness-native
		// spelling: TS must not reuse the conversationSummary.permission_mode
		// vocabulary (which does carry native spellings) for this key.
		{"StructuredTurnResult.completed_permission_mode", turnproto.StructuredTurnResult{
			Status: turnproto.StatusCompleted, Reply: "done", HarnessSessionID: "sess-7",
			TranscriptEntries: textEntries, WorkingDir: "/work",
			PermissionMode: "bypass",
		}},
	}
}

// TestConformance_TurnResultFields freezes the neutral field contract for the
// public StructuredTurnResult JSON form and its embedded types (transcript.Event
// — internal json:"-" fields excluded — and transcript.Usage).
func TestConformance_TurnResultFields(t *testing.T) {
	got, err := neutral.Marshal(neutral.FieldsFor(
		turnproto.StructuredTurnResult{},
		transcript.Event{},
		transcript.Usage{},
	))
	if err != nil {
		t.Fatalf("marshal neutral fields: %v", err)
	}
	assertConformanceGolden(t, filepath.Join("turnresult", "fields.json"), got)
}

// TestConformance_TurnResultFixtures emits each fixture under UPDATE_GOLDEN=1 and
// otherwise round-trips every golden through StructuredTurnResult asserting
// STRUCTURAL equality, including that omitempty optionals are absent in the
// absent-variant fixtures.
func TestConformance_TurnResultFixtures(t *testing.T) {
	for _, fx := range turnFixtures() {
		fx := fx
		t.Run(fx.name, func(t *testing.T) {
			path := filepath.Join("turnresult", fx.name+".json")
			if os.Getenv("UPDATE_GOLDEN") == "1" {
				data, err := json.MarshalIndent(fx.value, "", "  ")
				if err != nil {
					t.Fatalf("marshal fixture: %v", err)
				}
				writeConformanceFile(t, path, append(data, '\n'))
				return
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read golden %s (regenerate with make regen-conformance): %v", path, err)
			}
			assertRoundTripsStructurally(t, want, fx.value)
			assertOptionalKeys(t, want, fx.value)
		})
	}
}

// exitCodesFile is the frozen exit-code constants file. All four constants are
// pinned (ExitUsage is a RESERVED constant with no Go emit path); DeadlineLine
// is the frozen stderr anchor.
type exitCodesFile struct {
	ExitOK       int    `json:"ExitOK"`
	ExitError    int    `json:"ExitError"`
	ExitUsage    int    `json:"ExitUsage"`
	ExitDeadline int    `json:"ExitDeadline"`
	DeadlineLine string `json:"deadline_line"`
}

// pairing is one emit-pairing row: a status → (exit code, stderr anchor).
type pairing struct {
	ExitCode     int    `json:"exit_code"`
	StderrAnchor string `json:"stderr_anchor"`
}

// emitPairingTable builds the status → (exit_code, stderr_anchor) table from the
// ONE canonical authority every producer delegates to (turnproto.ExitCode) plus
// the frozen DeadlineLine. Only a deadline pairs with a stderr anchor; ExitUsage
// has no status row (no emit path).
func emitPairingTable() map[string]pairing {
	m := make(map[string]pairing, len(turnStatuses))
	for _, s := range turnStatuses {
		p := pairing{ExitCode: turnproto.ExitCode(s)}
		if s == turnproto.StatusDeadline {
			p.StderrAnchor = turnproto.DeadlineLine
		}
		m[string(s)] = p
	}
	return m
}

// TestConformance_CLIExitCodes freezes the exit-code constants and asserts they
// still equal pkg/turnproto's values (the corpus is DERIVED from the Go source
// of truth, never the other way round).
func TestConformance_CLIExitCodes(t *testing.T) {
	want := exitCodesFile{
		ExitOK:       turnproto.ExitOK,
		ExitError:    turnproto.ExitError,
		ExitUsage:    turnproto.ExitUsage,
		ExitDeadline: turnproto.ExitDeadline,
		DeadlineLine: turnproto.DeadlineLine,
	}
	data, err := json.MarshalIndent(want, "", "  ")
	if err != nil {
		t.Fatalf("marshal exit codes: %v", err)
	}
	assertConformanceGolden(t, filepath.Join("cli", "exit_codes.json"), append(data, '\n'))
}

// TestConformance_CLIEmitPairing freezes the status → (exit code, stderr anchor)
// table and asserts every row against turnproto.ExitCode — the single canonical
// table both the guest structured-run emit (cmd/harness-wrapper/structured_run.go)
// and the host client (pkg/env.RunStructuredTurn) delegate to. Pinning it here
// keeps the cross-language copy from drifting from that authority.
func TestConformance_CLIEmitPairing(t *testing.T) {
	table := emitPairingTable()
	data, err := json.MarshalIndent(table, "", "  ")
	if err != nil {
		t.Fatalf("marshal emit pairing: %v", err)
	}
	assertConformanceGolden(t, filepath.Join("cli", "emit_pairing.json"), append(data, '\n'))

	if os.Getenv("UPDATE_GOLDEN") == "1" {
		return
	}
	// Re-derive from the authority and assert the on-disk table agrees — this is
	// the anti-drift assertion, independent of the golden bytes.
	raw, err := os.ReadFile(filepath.Join("cli", "emit_pairing.json"))
	if err != nil {
		t.Fatalf("read emit_pairing.json: %v", err)
	}
	var onDisk map[string]pairing
	if err := json.Unmarshal(raw, &onDisk); err != nil {
		t.Fatalf("unmarshal emit_pairing.json: %v", err)
	}
	for _, s := range turnStatuses {
		row, ok := onDisk[string(s)]
		if !ok {
			t.Errorf("emit_pairing.json missing row for status %q", s)
			continue
		}
		if row.ExitCode != turnproto.ExitCode(s) {
			t.Errorf("status %q: table exit_code=%d, turnproto.ExitCode=%d", s, row.ExitCode, turnproto.ExitCode(s))
		}
		wantAnchor := ""
		if s == turnproto.StatusDeadline {
			wantAnchor = turnproto.DeadlineLine
		}
		if row.StderrAnchor != wantAnchor {
			t.Errorf("status %q: table stderr_anchor=%q, want %q", s, row.StderrAnchor, wantAnchor)
		}
	}
	// ExitUsage is a reserved constant with NO status → no emit_pairing row.
	if _, ok := onDisk["usage"]; ok {
		t.Errorf("emit_pairing.json has a 'usage' row; ExitUsage has no emit path")
	}
}

// TestConformance_Manifest recomputes MANIFEST.sha256 over EVERY corpus .json
// file (gateway/ + turnresult/ + cli/ + the fields files) and asserts it matches
// the committed manifest. The hash guards corpus-file integrity only (detects an
// unsynced / tampered vendored copy) — it is NOT a cross-language byte-identity
// claim. Declared LAST so under UPDATE_GOLDEN it hashes freshly-emitted bytes.
func TestConformance_Manifest(t *testing.T) {
	manifest, err := computeManifest(".")
	if err != nil {
		t.Fatalf("compute manifest: %v", err)
	}
	assertConformanceGolden(t, "MANIFEST.sha256", manifest)
}

// computeManifest walks root for *.json files and returns the sha256sum-style
// manifest: "<hex>  <relpath>\n" lines, sorted by forward-slash relative path.
// MANIFEST.sha256 itself and non-JSON files are excluded.
func computeManifest(root string) ([]byte, error) {
	type entry struct{ rel, sum string }
	var entries []entry
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".json") {
			return nil
		}
		data, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			return rerr
		}
		entries = append(entries, entry{rel: filepath.ToSlash(rel), sum: fmt.Sprintf("%x", sha256.Sum256(data))})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].rel < entries[j].rel })
	var b strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&b, "%s  %s\n", e.sum, e.rel)
	}
	return []byte(b.String()), nil
}

// assertRoundTripsStructurally parses golden into a fresh instance of value's
// type, re-serializes it, and asserts the re-serialized JSON is STRUCTURALLY
// identical to the golden (never a byte compare — §2). The prototype supplies
// only its type.
func assertRoundTripsStructurally(t *testing.T, golden []byte, prototype any) {
	t.Helper()
	var goldenGeneric any
	if err := json.Unmarshal(golden, &goldenGeneric); err != nil {
		t.Fatalf("golden is not valid JSON: %v", err)
	}
	dst := reflect.New(reflect.TypeOf(prototype)).Interface()
	if err := json.Unmarshal(golden, dst); err != nil {
		t.Fatalf("golden does not round-trip through %T: %v", prototype, err)
	}
	reser, err := json.Marshal(dst)
	if err != nil {
		t.Fatalf("re-serialize: %v", err)
	}
	var reserGeneric any
	if err := json.Unmarshal(reser, &reserGeneric); err != nil {
		t.Fatalf("re-serialized JSON invalid: %v", err)
	}
	if !reflect.DeepEqual(goldenGeneric, reserGeneric) {
		t.Errorf("structural drift round-tripping through %T\n--- golden ---\n%s\n--- re-serialized ---\n%s",
			prototype, golden, reser)
	}
}

// assertOptionalKeys checks that each omitempty optional on StructuredTurnResult
// is present in the golden JSON iff it is non-zero on the fixture value — proving
// the absent-variant fixtures actually omit the key (not emit a zero value).
func assertOptionalKeys(t *testing.T, golden []byte, value any) {
	t.Helper()
	res, ok := value.(turnproto.StructuredTurnResult)
	if !ok {
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(golden, &raw); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}
	checks := map[string]bool{
		"reason":           res.Reason != "",
		"transcript_error": res.TranscriptError != "",
		"usage":            res.Usage != nil,
		"permission_mode":  res.PermissionMode != "",
	}
	for key, wantPresent := range checks {
		_, present := raw[key]
		if present != wantPresent {
			t.Errorf("optional key %q present=%v, want %v", key, present, wantPresent)
		}
	}
}

// assertConformanceGolden emits under UPDATE_GOLDEN=1, else byte-compares. The
// generated files (fields.json, cli tables, fixtures, manifest) each have a
// deterministic canonical byte form owned by this generator, so a byte compare
// is valid — distinct from the STRUCTURAL comparison consumers apply to fixtures.
func assertConformanceGolden(t *testing.T, path string, got []byte) {
	t.Helper()
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		writeConformanceFile(t, path, got)
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %s (regenerate with make regen-conformance): %v", path, err)
	}
	if string(want) != string(got) {
		t.Errorf("conformance drift in %s — if intentional, regenerate with make regen-conformance\n--- got ---\n%s\n--- want ---\n%s",
			path, got, want)
	}
}

// writeConformanceFile creates parent dirs and writes a corpus file.
func writeConformanceFile(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
	t.Logf("updated %s", path)
}
