// Code generated by facadegen from github.com/olesho/harness-wrapper/internal/wrapcore. DO NOT EDIT.

package wrapper

import (
	"context"

	"github.com/olesho/harness-wrapper/internal/wrapcore"
)

// ClassifierInput is wrapcore.ClassifierInput.
type ClassifierInput = wrapcore.ClassifierInput

// Classification is wrapcore.Classification.
type Classification = wrapcore.Classification

// Classifier is wrapcore.Classifier.
type Classifier = wrapcore.Classifier

// ClassifierFunc is wrapcore.ClassifierFunc.
type ClassifierFunc = wrapcore.ClassifierFunc

// Containment is wrapcore.Containment.
type Containment = wrapcore.Containment

// ErrorClass is wrapcore.ErrorClass.
type ErrorClass = wrapcore.ErrorClass

// LoginConfig is wrapcore.LoginConfig.
type LoginConfig = wrapcore.LoginConfig

// LoginPrompt is wrapcore.LoginPrompt.
type LoginPrompt = wrapcore.LoginPrompt

// LoginResult is wrapcore.LoginResult.
type LoginResult = wrapcore.LoginResult

// Login is wrapcore.Login.
type Login = wrapcore.Login

// Snapshot is wrapcore.Snapshot.
type Snapshot = wrapcore.Snapshot

// SessionEvent is wrapcore.SessionEvent.
type SessionEvent = wrapcore.SessionEvent

// Session is wrapcore.Session.
type Session = wrapcore.Session

// Config is wrapcore.Config.
type Config = wrapcore.Config

// Status is wrapcore.Status.
type Status = wrapcore.Status

// Result is wrapcore.Result.
type Result = wrapcore.Result

// QueueLimits is wrapcore.QueueLimits.
type QueueLimits = wrapcore.QueueLimits

// Constants of wrapcore.
const (
	ContainmentLandlock      = wrapcore.ContainmentLandlock
	ErrNone                  = wrapcore.ErrNone
	ErrRateLimited           = wrapcore.ErrRateLimited
	ErrAuth                  = wrapcore.ErrAuth
	ErrBilling               = wrapcore.ErrBilling
	ErrModelNotFound         = wrapcore.ErrModelNotFound
	ErrContextOverflow       = wrapcore.ErrContextOverflow
	ErrTimeout               = wrapcore.ErrTimeout
	ErrTransient             = wrapcore.ErrTransient
	ErrUnknown               = wrapcore.ErrUnknown
	RuleTimeoutUpgrade       = wrapcore.RuleTimeoutUpgrade
	StatusIdle               = wrapcore.StatusIdle
	StatusFailed             = wrapcore.StatusFailed
	StatusBlockedByCost      = wrapcore.StatusBlockedByCost
	StatusRetryLater         = wrapcore.StatusRetryLater
	StatusAPIError           = wrapcore.StatusAPIError
	StatusWaitingForInput    = wrapcore.StatusWaitingForInput
	StatusStale              = wrapcore.StatusStale
	StatusInterrupted        = wrapcore.StatusInterrupted
	StatusUnknown            = wrapcore.StatusUnknown
	StatusBinaryNotFound     = wrapcore.StatusBinaryNotFound
	SkipPermissionsFlag      = wrapcore.SkipPermissionsFlag
	AllowSkipPermissionsFlag = wrapcore.AllowSkipPermissionsFlag
)

// Variables of wrapcore. Each holds the same value as its original, so errors.Is
// and comparisons match either.
var (
	ErrSessionTerminated      = wrapcore.ErrSessionTerminated
	ErrContainmentUnsupported = wrapcore.ErrContainmentUnsupported
	ErrContainmentRefused     = wrapcore.ErrContainmentRefused
	ErrLaunchDenied           = wrapcore.ErrLaunchDenied
	ErrInvalidConfig          = wrapcore.ErrInvalidConfig
	ErrBinaryNotFound         = wrapcore.ErrBinaryNotFound
	ErrPTYAllocation          = wrapcore.ErrPTYAllocation
	ErrPTYRead                = wrapcore.ErrPTYRead
	ErrClassifierPanic        = wrapcore.ErrClassifierPanic
)

// ClassifyOutput calls wrapcore.ClassifyOutput.
func ClassifyOutput(harness string, output string) Classification {
	return wrapcore.ClassifyOutput(harness, output)
}

// ClassifyFinishedOutput calls wrapcore.ClassifyFinishedOutput.
func ClassifyFinishedOutput(harness string, output string) Classification {
	return wrapcore.ClassifyFinishedOutput(harness, output)
}

// StartLogin calls wrapcore.StartLogin.
func StartLogin(ctx context.Context, cfg LoginConfig) (*Login, error) {
	return wrapcore.StartLogin(ctx, cfg)
}

// LoginStatus calls wrapcore.LoginStatus.
func LoginStatus(ctx context.Context, cfg LoginConfig) (LoginResult, error) {
	return wrapcore.LoginStatus(ctx, cfg)
}

// Run calls wrapcore.Run.
func Run(ctx context.Context, cfg Config) (Result, error) {
	return wrapcore.Run(ctx, cfg)
}

// Start calls wrapcore.Start.
func Start(ctx context.Context, cfg Config) (*Session, error) {
	return wrapcore.Start(ctx, cfg)
}

// HarnessArgs calls wrapcore.HarnessArgs.
func HarnessArgs(cfg Config) ([]string, error) {
	return wrapcore.HarnessArgs(cfg)
}

// IsBypassPermissionMode calls wrapcore.IsBypassPermissionMode.
func IsBypassPermissionMode(mode string) bool {
	return wrapcore.IsBypassPermissionMode(mode)
}

// PermissionRungs calls wrapcore.PermissionRungs.
func PermissionRungs() []string {
	return wrapcore.PermissionRungs()
}

// MorePermissive calls wrapcore.MorePermissive.
func MorePermissive(a string, b string) bool {
	return wrapcore.MorePermissive(a, b)
}

// BypassEnablingFlags calls wrapcore.BypassEnablingFlags.
func BypassEnablingFlags(harness string) []string {
	return wrapcore.BypassEnablingFlags(harness)
}

// BypassReachableFlags calls wrapcore.BypassReachableFlags.
func BypassReachableFlags(harness string) []string {
	return wrapcore.BypassReachableFlags(harness)
}

// EffectiveLaunchRung calls wrapcore.EffectiveLaunchRung.
func EffectiveLaunchRung(harness string, args []string, mode string) string {
	return wrapcore.EffectiveLaunchRung(harness, args, mode)
}
