// Code generated by facadegen from github.com/olesho/harness-wrapper/internal/chatcore. DO NOT EDIT.

package chat

import (
	"context"

	"github.com/olesho/harness-wrapper/internal/chatcore"
	"github.com/olesho/harness-wrapper/pkg/discovery/models"
)

// Role is chatcore.Role.
type Role = chatcore.Role

// TurnState is chatcore.TurnState.
type TurnState = chatcore.TurnState

// TurnCode is chatcore.TurnCode.
type TurnCode = chatcore.TurnCode

// Turn is chatcore.Turn.
type Turn = chatcore.Turn

// Transport is chatcore.Transport.
type Transport = chatcore.Transport

// EventType is chatcore.EventType.
type EventType = chatcore.EventType

// RateLimitStatus is chatcore.RateLimitStatus.
type RateLimitStatus = chatcore.RateLimitStatus

// RateLimit is chatcore.RateLimit.
type RateLimit = chatcore.RateLimit

// RateLimitWindow is chatcore.RateLimitWindow.
type RateLimitWindow = chatcore.RateLimitWindow

// ConversationEvent is chatcore.ConversationEvent.
type ConversationEvent = chatcore.ConversationEvent

// Session is chatcore.Session.
type Session = chatcore.Session

// SessionContainment is chatcore.SessionContainment.
type SessionContainment = chatcore.SessionContainment

// ContainmentStore is chatcore.ContainmentStore.
type ContainmentStore = chatcore.ContainmentStore

// Options is chatcore.Options.
type Options = chatcore.Options

// Conversation is chatcore.Conversation.
type Conversation = chatcore.Conversation

// ReopenOptions is chatcore.ReopenOptions.
type ReopenOptions = chatcore.ReopenOptions

// HistorySource is chatcore.HistorySource.
type HistorySource = chatcore.HistorySource

// InputUnresolvedError is chatcore.InputUnresolvedError.
type InputUnresolvedError = chatcore.InputUnresolvedError

// DiscoverModelsOptions is chatcore.DiscoverModelsOptions.
type DiscoverModelsOptions = chatcore.DiscoverModelsOptions

// ExitInfo is chatcore.ExitInfo.
type ExitInfo = chatcore.ExitInfo

// State is chatcore.State.
type State = chatcore.State

// DeliveryState is chatcore.DeliveryState.
type DeliveryState = chatcore.DeliveryState

// InputRequest is chatcore.InputRequest.
type InputRequest = chatcore.InputRequest

// InputOption is chatcore.InputOption.
type InputOption = chatcore.InputOption

// InputAnswer is chatcore.InputAnswer.
type InputAnswer = chatcore.InputAnswer

// DispositionKind is chatcore.DispositionKind.
type DispositionKind = chatcore.DispositionKind

// Disposition is chatcore.Disposition.
type Disposition = chatcore.Disposition

// InputPolicy is chatcore.InputPolicy.
type InputPolicy = chatcore.InputPolicy

// InterruptResult is chatcore.InterruptResult.
type InterruptResult = chatcore.InterruptResult

// PermissionModeBlockedError is chatcore.PermissionModeBlockedError.
type PermissionModeBlockedError = chatcore.PermissionModeBlockedError

// ScreenAnchor is chatcore.ScreenAnchor.
type ScreenAnchor = chatcore.ScreenAnchor

// Store is chatcore.Store.
type Store = chatcore.Store

// Constants of chatcore.
const (
	RoleUser                  = chatcore.RoleUser
	RoleAssistant             = chatcore.RoleAssistant
	RoleSystem                = chatcore.RoleSystem
	TurnStatePending          = chatcore.TurnStatePending
	TurnStateStreaming        = chatcore.TurnStateStreaming
	TurnStateComplete         = chatcore.TurnStateComplete
	TurnStateErrored          = chatcore.TurnStateErrored
	TurnStateInterrupted      = chatcore.TurnStateInterrupted
	ReasonAuthRequired        = chatcore.ReasonAuthRequired
	ReasonUsageLimited        = chatcore.ReasonUsageLimited
	ReasonBillingWall         = chatcore.ReasonBillingWall
	CodeAuthRequired          = chatcore.CodeAuthRequired
	CodeUsageLimited          = chatcore.CodeUsageLimited
	CodeBillingWall           = chatcore.CodeBillingWall
	TransportTUI              = chatcore.TransportTUI
	TransportStreamJSON       = chatcore.TransportStreamJSON
	EventTurn                 = chatcore.EventTurn
	EventInputRequest         = chatcore.EventInputRequest
	EventInputResolved        = chatcore.EventInputResolved
	EventExited               = chatcore.EventExited
	EventRateLimit            = chatcore.EventRateLimit
	RateLimitAllowed          = chatcore.RateLimitAllowed
	RateLimitWarning          = chatcore.RateLimitWarning
	RateLimitRejected         = chatcore.RateLimitRejected
	RateLimitUnknown          = chatcore.RateLimitUnknown
	ContainmentRecordVersion  = chatcore.ContainmentRecordVersion
	HistorySourceTranscript   = chatcore.HistorySourceTranscript
	HistorySourceStore        = chatcore.HistorySourceStore
	DispositionAsk            = chatcore.DispositionAsk
	DispositionAnswer         = chatcore.DispositionAnswer
	DispositionDeny           = chatcore.DispositionDeny
	InterruptStopped          = chatcore.InterruptStopped
	InterruptCancelled        = chatcore.InterruptCancelled
	InterruptNoTurn           = chatcore.InterruptNoTurn
	InterruptTooLate          = chatcore.InterruptTooLate
	DiagTranscriptUnavailable = chatcore.DiagTranscriptUnavailable
)

// Variables of chatcore. Each holds the same value as its original, so errors.Is
// and comparisons match either.
var (
	ErrInvalidOptions               = chatcore.ErrInvalidOptions
	ErrUnknownHarness               = chatcore.ErrUnknownHarness
	ErrNoControl                    = chatcore.ErrNoControl
	ErrTurnInFlight                 = chatcore.ErrTurnInFlight
	ErrClosed                       = chatcore.ErrClosed
	ErrInputPending                 = chatcore.ErrInputPending
	ErrAuthRequired                 = chatcore.ErrAuthRequired
	ErrUnrecognizedDialog           = chatcore.ErrUnrecognizedDialog
	ErrHarnessBusy                  = chatcore.ErrHarnessBusy
	ErrInterruptUnsupported         = chatcore.ErrInterruptUnsupported
	ErrInterruptUnconfirmed         = chatcore.ErrInterruptUnconfirmed
	ErrComposerNotCleared           = chatcore.ErrComposerNotCleared
	ErrExited                       = chatcore.ErrExited
	ErrEventTooLarge                = chatcore.ErrEventTooLarge
	ErrUndelivered                  = chatcore.ErrUndelivered
	ErrHarnessSessionIDNotSaved     = chatcore.ErrHarnessSessionIDNotSaved
	ErrNoInputPending               = chatcore.ErrNoInputPending
	ErrStaleInputRequest            = chatcore.ErrStaleInputRequest
	ErrUnknownOption                = chatcore.ErrUnknownOption
	ErrNotMultiSelect               = chatcore.ErrNotMultiSelect
	ErrConflictingAnswer            = chatcore.ErrConflictingAnswer
	ErrQuitUnsupported              = chatcore.ErrQuitUnsupported
	ErrResumeUnsupported            = chatcore.ErrResumeUnsupported
	ErrNoHarnessSession             = chatcore.ErrNoHarnessSession
	ErrHarnessSessionInUse          = chatcore.ErrHarnessSessionInUse
	ErrContainmentUnavailable       = chatcore.ErrContainmentUnavailable
	ErrInputUnresolved              = chatcore.ErrInputUnresolved
	ErrPickerUnsupported            = chatcore.ErrPickerUnsupported
	ErrPickerTimeout                = chatcore.ErrPickerTimeout
	ErrPermissionModeUnsupported    = chatcore.ErrPermissionModeUnsupported
	ErrPermissionModeUnreachable    = chatcore.ErrPermissionModeUnreachable
	ErrPermissionModeSwitchFailed   = chatcore.ErrPermissionModeSwitchFailed
	ErrPermissionModeIndeterminate  = chatcore.ErrPermissionModeIndeterminate
	ErrPermissionModeBlockedByInput = chatcore.ErrPermissionModeBlockedByInput
	ErrCodexPlanRefusedBusy         = chatcore.ErrCodexPlanRefusedBusy
)

// DeleteContainmentState calls chatcore.DeleteContainmentState.
func DeleteContainmentState(ctx context.Context, store Store, sessionID string) error {
	return chatcore.DeleteContainmentState(ctx, store, sessionID)
}

// Open calls chatcore.Open.
func Open(ctx context.Context, opts Options) (*Conversation, error) {
	return chatcore.Open(ctx, opts)
}

// Reopen calls chatcore.Reopen.
func Reopen(ctx context.Context, opts ReopenOptions) (*Conversation, error) {
	return chatcore.Reopen(ctx, opts)
}

// DiscoverModels calls chatcore.DiscoverModels.
func DiscoverModels(ctx context.Context, opts DiscoverModelsOptions) ([]models.Info, error) {
	return chatcore.DiscoverModels(ctx, opts)
}

// AuthAnchors calls chatcore.AuthAnchors.
func AuthAnchors(harness string) []ScreenAnchor {
	return chatcore.AuthAnchors(harness)
}

// DialogAnchors calls chatcore.DialogAnchors.
func DialogAnchors(harness string) []string {
	return chatcore.DialogAnchors(harness)
}
