// Code generated by facadegen from github.com/olesho/harness-wrapper/internal/harnesscore. DO NOT EDIT.

package harness

import (
	"github.com/olesho/harness-wrapper/internal/harnesscore"
	"github.com/olesho/harness-wrapper/pkg/transcript"
)

// Profile is harnesscore.Profile.
type Profile = harnesscore.Profile

// ResolveContext is harnesscore.ResolveContext.
type ResolveContext = harnesscore.ResolveContext

// ResolvedProfile is harnesscore.ResolvedProfile.
type ResolvedProfile = harnesscore.ResolvedProfile

// SessionIDExtractor is harnesscore.SessionIDExtractor.
type SessionIDExtractor = harnesscore.SessionIDExtractor

// Resumer is harnesscore.Resumer.
type Resumer = harnesscore.Resumer

// StreamParser is harnesscore.StreamParser.
type StreamParser = harnesscore.StreamParser

// SpoolReceipt is harnesscore.SpoolReceipt.
type SpoolReceipt = harnesscore.SpoolReceipt

// SpoolBatch is harnesscore.SpoolBatch.
type SpoolBatch = harnesscore.SpoolBatch

// SpoolQuarantine is harnesscore.SpoolQuarantine.
type SpoolQuarantine = harnesscore.SpoolQuarantine

// SpoolContents is harnesscore.SpoolContents.
type SpoolContents = harnesscore.SpoolContents

// HookProvider is harnesscore.HookProvider.
type HookProvider = harnesscore.HookProvider

// ToolHookProvider is harnesscore.ToolHookProvider.
type ToolHookProvider = harnesscore.ToolHookProvider

// StaticHookProfile is harnesscore.StaticHookProfile.
type StaticHookProfile = harnesscore.StaticHookProfile

// ConfigDirResolver is harnesscore.ConfigDirResolver.
type ConfigDirResolver = harnesscore.ConfigDirResolver

// HookContext is harnesscore.HookContext.
type HookContext = harnesscore.HookContext

// HookSpec is harnesscore.HookSpec.
type HookSpec = harnesscore.HookSpec

// HookEntry is harnesscore.HookEntry.
type HookEntry = harnesscore.HookEntry

// Mode is harnesscore.Mode.
type Mode = harnesscore.Mode

// SettingsHookMatcher is harnesscore.SettingsHookMatcher.
type SettingsHookMatcher = harnesscore.SettingsHookMatcher

// SettingsHookCmd is harnesscore.SettingsHookCmd.
type SettingsHookCmd = harnesscore.SettingsHookCmd

// YieldControl is harnesscore.YieldControl.
type YieldControl = harnesscore.YieldControl

// HookOutcome is harnesscore.HookOutcome.
type HookOutcome = harnesscore.HookOutcome

// Constants of harnesscore.
const (
	EnvSpool                  = harnesscore.EnvSpool
	EnvHookCwd                = harnesscore.EnvHookCwd
	EnvHome                   = harnesscore.EnvHome
	EnvConfigDir              = harnesscore.EnvConfigDir
	EnvHarnessSessionID       = harnesscore.EnvHarnessSessionID
	MaxSpoolFileBytes         = harnesscore.MaxSpoolFileBytes
	SpoolQuarantineDir        = harnesscore.SpoolQuarantineDir
	MaxSpoolQuarantine        = harnesscore.MaxSpoolQuarantine
	HookArgPreToolUse         = harnesscore.HookArgPreToolUse
	HookArgPostToolUse        = harnesscore.HookArgPostToolUse
	HookArgPostToolUseFailure = harnesscore.HookArgPostToolUseFailure
	HookArgSubagentStart      = harnesscore.HookArgSubagentStart
	HookArgSubagentStop       = harnesscore.HookArgSubagentStop
	MaxToolHookBytes          = harnesscore.MaxToolHookBytes
	ToolHookTruncated         = harnesscore.ToolHookTruncated
	TranscriptOff             = harnesscore.TranscriptOff
	TranscriptStreamParse     = harnesscore.TranscriptStreamParse
	TranscriptHooks           = harnesscore.TranscriptHooks
	TranscriptAuto            = harnesscore.TranscriptAuto
	EnvYieldFile              = harnesscore.EnvYieldFile
)

// Variables of harnesscore. Each holds the same value as its original, so errors.Is
// and comparisons match either.
var (
	ErrSpoolReceipt = harnesscore.ErrSpoolReceipt
)

// Register calls harnesscore.Register.
func Register(name string, p Profile) {
	harnesscore.Register(name, p)
}

// For calls harnesscore.For.
func For(name string) (Profile, bool) {
	return harnesscore.For(name)
}

// Registered calls harnesscore.Registered.
func Registered() []string {
	return harnesscore.Registered()
}

// IsManagedHookCommand calls harnesscore.IsManagedHookCommand.
func IsManagedHookCommand(command string) bool {
	return harnesscore.IsManagedHookCommand(command)
}

// RenderHookCommand calls harnesscore.RenderHookCommand.
func RenderHookCommand(loomArgv []string, harnessName string, arg string, owner string) string {
	return harnesscore.RenderHookCommand(loomArgv, harnessName, arg, owner)
}

// WithLockedFile calls harnesscore.WithLockedFile.
func WithLockedFile(targetPath string, fn func(existing []byte) ([]byte, error)) error {
	return harnesscore.WithLockedFile(targetPath, fn)
}

// HandleHookEvent calls harnesscore.HandleHookEvent.
func HandleHookEvent(harnessName string, event string, env []string, stdin []byte) (HookOutcome, error) {
	return harnesscore.HandleHookEvent(harnessName, event, env, stdin)
}

// DrainSpool calls harnesscore.DrainSpool.
func DrainSpool(spoolDir string) ([]transcript.ParsedEvent, error) {
	return harnesscore.DrainSpool(spoolDir)
}

// ReadSpool calls harnesscore.ReadSpool.
func ReadSpool(spoolDir string) (SpoolContents, error) {
	return harnesscore.ReadSpool(spoolDir)
}

// ParseSpoolFileName calls harnesscore.ParseSpoolFileName.
func ParseSpoolFileName(name string) (event string, nanos int64, ok bool) {
	return harnesscore.ParseSpoolFileName(name)
}

// AckSpool calls harnesscore.AckSpool.
func AckSpool(spoolDir string, receipts ...SpoolReceipt) error {
	return harnesscore.AckSpool(spoolDir, receipts...)
}

// EnvLookup calls harnesscore.EnvLookup.
func EnvLookup(env []string, key string) string {
	return harnesscore.EnvLookup(env, key)
}

// EnsureSettingsJSONHooks calls harnesscore.EnsureSettingsJSONHooks.
func EnsureSettingsJSONHooks(settingsPath string, spec *HookSpec, loomArgv []string, harnessName string) error {
	return harnesscore.EnsureSettingsJSONHooks(settingsPath, spec, loomArgv, harnessName)
}

// NewYieldControl calls harnesscore.NewYieldControl.
func NewYieldControl() (*YieldControl, error) {
	return harnesscore.NewYieldControl()
}
